version: '3'

services:
  frontend:
    build: ./super-pancake/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./super-pancake/backend
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://mongodb:27017/mydatabase"

  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
