version: '3'

services:
  react-frontend:
    build: /Users/lokosrobert/Desktop/SuperPancake/super-pancake/react-frontend
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - backend
    volumes:
      - /Users/lokosrobert/Desktop/SuperPancake/super-pancake/react-frontend:/usr/src/super-pancake/react-frontend
      - /usr/src/super-pancake/react-frontend/node_modules

  backend:
    build: /Users/lokosrobert/Desktop/SuperPancake/super-pancake/backend
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - mongodb
      - mysqldb
    environment:
      MONGO_URI: "mongodb://mongodb:27017/mydatabase"
      MYSQL_HOST: "mysql"
      MYSQL_PORT: "3306"
    volumes:
      - /Users/lokosrobert/Desktop/SuperPancake/super-pancake/backend:/usr/src/super-pancake/backend

  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
    restart: always

  mysqldb:
    image: "mysql:latest"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "pancake"
      MYSQL_USER: "robi"
      MYSQL_PASSWORD: "test"